### ISSUE TITLE
HSL to HSV conversion incorrect

### ISSUE THREAD

**Issue by matthew-banning** [ozdemirburak/iris#27]
The conversion from HSL to HSV appears incorrect:
```
echo Factory::init("hsv(0, 50%, 50%)")->toHsl() // hsl(0, 33%, 38%) (correct values)
echo Factory::init("hsv(0, 50%, 50%)")->toHsl()->toHsv() // hsv(0,100%,76%) (wrong values)
```

**Comment by ozdemirburak** [comment]
You are right. Thanks for reporting this. I'll patch it now. But the second example will probably give an error because of rounding as 50.5 will become 51. So, try: "hsv(0, 50%, 51%)". See a [related discussion here](https://stackoverflow.com/questions/45471944/how-to-keep-rgb-and-hsl-integer-values-consistent-when-converting-back-and-forth). I am open to any solutions, though.
